import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import Header from './_components/Header';
import Footer from './_components/Footer';

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
});

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="sv-SE" className="h-full bg-gray-100">
            <body className={`${geistSans.variable} ${geistMono.variable} antialiased h-full`}>
                {/* Flexbox for a pancake layout */}
                <div className="flex flex-col min-h-screen">
                    {/* Header at the top */}
                    <Header />

                    {/* Main content grows to fill the viewport */}
                    <main className="flex-1 container mx-auto py-6 px-4">{children}</main>

                    {/* Footer at the bottom */}
                    <Footer />
                </div>
            </body>
        </html>
    );
}
